# -*- coding: utf-8 -*-
# LAST WAVE 사이트 콘텐츠 — 영웅·위협·아레나·소식. 그림은 대표가 만든 site_art 만 쓴다.

HEROES = [
 dict(id="pixel", name="PIXEL", ko="픽셀", role="MAIN", roleKo="주인공", hp=200, combo="20 · 25 · 30", art=True,
  tag_ko="WAVE와 깊은 관계가 있는 정체불명의 인물. 가면은 벗지 않는다.",
  tag_en="A figure of unknown origin, bound to the WAVE. The mask never comes off.",
  bio_ko=["손끝의 푸른 빛은 파도와 같은 것으로 만들어졌다. 그래서 파도를 밀어내고, 쓰러진 동료를 되살리고, 픽셀로 흩어졌다가 다시 모인다.",
          "서울역 지하 연구소의 기록에는 「PROJECT: PIXEL」이라는 이름이 남아 있다. 그는 만들어진 존재인가, 아니면 균열이 처음 열린 자리 그 자체인가.",
          "말이 없다. 대신 마지막 기술 BLUE PILLAR가 파도의 심장을 그대로 찌른다."],
  bio_en=["The blue light at his fingertips is made of the same thing as the wave. So he pushes the wave back, brings fallen allies up, scatters into pixels and reforms.",
          "Records from the lab beneath Seoul Station carry one name: PROJECT: PIXEL. Was he made — or is he the place where the rift first opened?",
          "He does not speak. His last skill, BLUE PILLAR, drives straight into the heart of the wave."],
  quote_ko="가면은 얼굴이 아니라 약속이다.", quote_en="The mask is not a face. It is a promise.",
  skills=[("Q","TSUNAMI","거대한 푸른 파도 100 + 넉백","A vast blue wave · 100 + knockback","wave"),
          ("E","TEAM HEAL","푸른 파동 회복 +80","Blue pulse · heal +80","pulse"),
          ("C","TELEPORT","푸른 픽셀로 흩어져 순간이동 · 무적","Scatter into pixels · blink · invulnerable","blink"),
          ("X","BLUE PILLAR","일반 워커 즉사 · 보스 2,500","Kills walkers outright · 2,500 to bosses","pillar")]),
 dict(id="bluenewbie", name="BLUE NEWBIE", ko="블루뉴비", role="MEDIC", roleKo="회복", hp=300, combo="15 · 15 · 25", art=False,
  tag_ko="회복 전문. 공격은 약하지만 버티는 힘이 누구보다 강하다.", tag_en="The medic. Weak strikes, the strongest will to stay standing.",
  bio_ko=["안경 너머로 팀 전체의 체력을 본다. 네 기술 전부가 「남을 살리는」 것이고, 그래서 영웅 중 유일하게 HP가 300이다.",
          "블루 웨빙 스트랩은 장식이 아니다. 밤새 뛰어다니며 쓰러진 사람을 끌어올린 흔적이다."],
  bio_en=["Behind the glasses he watches the whole team's health. All four skills exist to keep others alive — which is why he alone carries 300 HP.",
          "The blue webbing straps are not decoration. They are what is left after nights of dragging people back up."],
  quote_ko="내가 서 있는 한, 아무도 안 죽어.", quote_en="As long as I'm standing, nobody dies.",
  skills=[("Q","HEAL LINK","회복 링크 · 초당 +15 (8초)","Heal link · +15/s for 8s","link"),("E","HEAL BURST","즉시 +100 회복","Instant +100","burst"),
          ("C","LIFE SHIELD","100 흡수 보호막 · 깨지면 +50 회복","100 shield · +50 heal on break","shield"),("X","ALL HEAL","완전 회복 +200 · 무적 1초","Full heal +200 · 1s invulnerable","all")]),
 dict(id="rookie", name="ROOKIE", ko="루키", role="STARTER", roleKo="시작", hp=200, combo="15 · 15 · 20", art=False,
  tag_ko="WAVE가 시작된 그날, 평범한 생존자였던 그는 살아남기 위해 싸우기 시작했다.", tag_en="On the day the WAVE began, an ordinary survivor started fighting to stay alive.",
  bio_ko=["기술이 아니라 몸으로 싸운다. 대시, 펀치, 가드 — 그리고 10초의 각성.", "모든 플레이어가 처음 만나는 얼굴. 강남에서 친구들을 잃고, 지하철 입구에서 처음 워커를 쓰러뜨렸다."],
  bio_en=["He fights with his body, not with tricks. Dash, punch, guard — and ten seconds of awakening.", "The first face every player meets. Lost his friends in Gangnam, dropped his first walker at the station entrance."],
  quote_ko="도망치는 것도 싸우는 거다. 오늘까지는.", quote_en="Running is fighting too. Until today.",
  skills=[("Q","DASH","전방 대시 · 잠시 무적","Forward dash · brief invulnerability","dash"),("E","POWER PUNCH","강력한 펀치 40","Heavy punch · 40","punch"),
          ("C","GUARD","2초간 받는 피해 50% 감소","−50% damage taken for 2s","guard"),("X","FULL POWER","10초 각성 · 공격 +50% · 속도 +30%","10s awakening · +50% attack · +30% speed","power")]),
 dict(id="alfred", name="ALFRED", ko="알프레드", role="DRAGONS", roleKo="쌍룡", hp=200, combo="18 · 18 · 35", art=True,
  tag_ko="양 어깨에 붙은 두 마리 네온 용과 함께 싸운다. 모든 기술은 용에서 나온다.", tag_en="Fights with two neon dragons on his shoulders. Every skill comes from them.",
  bio_ko=["푸른 용과 보라 용. 앞서 달리고, 포효하고, 몸을 감아 지키고, 적을 하늘로 끌고 가 내리꽂는다.", "후드의 「001」은 번호가 아니라 이름이다. 용은 무기가 아니라 동료다."],
  bio_en=["Blue and violet. They run ahead, roar, coil around him as a shield, and drag enemies into the sky to slam them down.", "The 001 on his hoodie is not a number, it is a name. The dragons are not weapons. They are company."],
  quote_ko="둘이 아니라 셋이야.", quote_en="Not two of us. Three.",
  skills=[("Q","RAINBOW DASH","두 용이 앞서 달린다 · 돌진 + 무지개 잔상 30×3","The dragons run ahead · charge + rainbow trail 30×3","dash"),
          ("E","SHOCKWAVE","두 용의 포효 · 충격파 80 + 넉백","Twin roar · shockwave 80 + knockback","wave"),
          ("C","PRISM SHIELD","용들이 몸을 감는다 · 방어막 100 · 깨지면 폭발 60","The dragons coil · shield 100 · bursts for 60","shield"),
          ("X","DRAGON FALL","두 용이 적을 물어 하늘로 끌고 가 내리꽂는다 1,000","Both dragons drag the enemy skyward and slam it down · 1,000","pillar")]),
 dict(id="line", name="LINE", ko="라인", role="BLADE", roleKo="대검", hp=200, combo="25 · 30 · 45", art=False,
  tag_ko="거대한 대검. 직육면체 머리는 헬멧이 아니라 그 자체가 얼굴이다.", tag_en="A giant blade. The block-shaped head is not a helmet — it is the face.",
  bio_ko=["검을 키우고, 바닥에서 불러내고, 적을 검 쪽으로 끌어당기고, 열다섯 자루를 연속으로 던진다.", "표정이 없어서 가장 무섭다. 어디서 왔는지 아무도 묻지 않았다."],
  bio_en=["Grows the blade, calls blades up from the ground, pulls enemies toward it, throws fifteen in a row.", "No expression — which is what makes him the most frightening. Nobody ever asked where he came from."],
  quote_ko="선을 넘었으면, 잘린다.", quote_en="Cross the line, and you're cut.",
  skills=[("Q","GIANT BLADE","검이 거대해진다 · 공격 +60% · 주변 10","The blade grows · +60% attack · 10 around","blade"),("E","BLADE SUMMON","바닥에서 검 소환 · 적마다 40","Blades from the ground · 40 each","summon"),
          ("C","MAGNET BLADE","적들을 검 쪽으로 끌어당김 20","Pulls enemies to the blade · 20","magnet"),("X","15 BLADES","검 15자루 연속 투척 70×15","Fifteen blades thrown · 70×15","multi")]),
]

THREATS = [
 dict(id="lurker", name="LURKER", ko="러커", wave=1, hp=80, dmg=10, speed="보통", speed_en="Normal", kind="근접", kind_en="Melee",
  ko_d="가장 먼저 오는 것. 어둠에서 태어나, 어둠으로 돌아간다.", en_d="The first to come. Born from the dark, returning to it."),
 dict(id="runner", name="RUNNER", ko="러너", wave=3, hp=60, dmg=8, speed="매우 빠름", speed_en="Very fast", kind="근접", kind_en="Melee",
  ko_d="중거리에서 한 번씩 달려든다. 잔상이 보이면 이미 늦다.", en_d="Lunges from mid range. If you see the afterimage, it is already too late."),
 dict(id="brute", name="BRUTE", ko="브루트", wave=5, hp=500, dmg=35, speed="느림", speed_en="Slow", kind="강타", kind_en="Heavy",
  ko_d="느리지만 한 방이 35. 바위가 걸어온다.", en_d="Slow, but one blow is 35. The rock walks."),
 dict(id="spitter", name="SPITTER", ko="스피터", wave=7, hp=100, dmg=15, speed="느림", speed_en="Slow", kind="원거리", kind_en="Ranged",
  ko_d="거리를 두고 뱉는다. 초록빛을 보면 옆으로.", en_d="Keeps its distance and spits. Green light — step aside."),
 dict(id="crawler", name="CRAWLER", ko="크롤러", wave=8, hp=120, dmg=20, speed="빠름", speed_en="Fast", kind="기어옴", kind_en="Crawler",
  ko_d="낮게, 빠르게. 바닥을 보지 않으면 먼저 물린다.", en_d="Low and fast. Watch the ground or it bites first."),
 dict(id="hunter", name="HUNTER", ko="헌터", wave=11, hp=250, dmg=30, speed="빠름", speed_en="Fast", kind="근접", kind_en="Melee",
  ko_d="선로 위를 달린다. 그들은 PIXEL만 노린다.", en_d="Runs the rails. They hunt only PIXEL."),
 dict(id="reaper", name="REAPER", ko="리퍼", wave=16, hp=400, dmg=40, speed="보통", speed_en="Normal", kind="강타", kind_en="Heavy",
  ko_d="후반의 벽. 낫이 푸르게 빛나면 한 명은 사라진다.", en_d="The late-game wall. When the scythe glows blue, someone is gone."),
]
BOSSES = [
 dict(id="themarked", name="THE MARKED", ko="표식을 가진 자", wave=10, hp=3000, dmg=25, phases=1,
  ko_d="광화문 광장에서 기다린다. 가면의 문양이 PIXEL의 것과 같다.", en_d="Waits in Gwanghwamun Square. The sigil on its face matches PIXEL's mask."),
 dict(id="voidtitan", name="VOID TITAN", ko="보이드 타이탄", wave=20, hp=5000, dmg=30, phases=3,
  ko_d="롯데타워가 균열을 붙잡고 있다. 그 위에 타이탄이 있다. 3페이즈.", en_d="Lotte Tower holds the rift shut. The Titan stands on top of it. Three phases."),
]

ARENAS = [
 ("GANGNAM","강남 폐허 거리","1–5","균열이 열린 날, 나는 강남에 있었다. 친구들은… 보이지 않는다.","The day the rift opened, I was in Gangnam. My friends… gone."),
 ("STATION","지하철 입구 광장","6–10","지하로 내려간 사람들은 돌아오지 않았다. 워커는 어둠에서 태어난다.","Those who went underground never came back. Walkers are born in the dark."),
 ("HAN RIVER","한강 다리","11–15","다리를 건너면 북쪽이다. 남산타워가 부러진 채 서 있다.","Across the bridge is the north. Namsan Tower stands, broken."),
 ("MYEONGDONG","명동 거리","16–20","명동은 조용했다. 조용한 곳이 가장 위험하다.","Myeongdong was quiet. Quiet places are the most dangerous."),
 ("HONGDAE","홍대 거리","21–25","네온이 아직 깜박인다. 누군가 여기서 마지막 밤을 보냈다.","The neon still flickers. Someone spent their last night here."),
 ("GWANGHWAMUN","광화문 광장","26–30","THE MARKED가 여기서 나를 기다린다. 가면의 문양이… 내 것과 같다.","THE MARKED waits for me here. The sigil on its face… is mine."),
 ("SEOUL STATION","서울역 광장","31–35","PROJECT: PIXEL — 서울역 지하 연구소의 기록. 나는… 만들어진 존재였나.","PROJECT: PIXEL — records from the lab beneath Seoul Station. Was I… made?"),
 ("PLATFORM","지하철 승강장","36–40","HUNTER들이 선로 위를 달린다. 그들은 나만 노린다.","HUNTERS run the rails. They hunt only me."),
 ("BUKCHON","북촌 한옥마을","41–45","가장 오래된 골목. 균열이 처음 열린 곳은 여기가 아니다 — 나였다.","The oldest alley. The rift did not open here first — it opened in me."),
 ("LOTTE TOWER","잠실 롯데타워","46–49","타워가 균열을 붙잡고 있다. VOID TITAN이 그 위에 있다.","The tower holds the rift. VOID TITAN stands on top."),
 ("THE RIFT","균열 내부","50","균열 안. 여기서 끝낸다.","Inside the rift. It ends here."),
]

NEWS = [
 ("2026-09-24","캐릭터 아트 1차 공개","PIXEL · ALFRED와 적 7종, 보스 2종의 키아트가 나왔다. BLUE NEWBIE · ROOKIE · LINE은 원본 디자인 기준으로 제작 중.",
  "First character art","Key art for PIXEL, ALFRED, seven enemies and two bosses. BLUE NEWBIE, ROOKIE and LINE are in production from their original designs."),
 ("2026-09-23","리얼 3D로 간다","스타일라이즈드 목업을 기각하고 반실사 3D(Unity)로 전환했다. 천천히 가더라도 제대로. 3D 초판은 영웅 2 · 적 3 · 보스 1.",
  "Going real-3D","Stylized mockups were rejected; the game moves to semi-realistic 3D in Unity. Slowly, but properly. First 3D cut: 2 heroes, 3 enemies, 1 boss."),
 ("2026-09-24","인트로 영상 갱신","PIXEL의 검은 가면과 블루 X, BLUE NEWBIE의 새 디자인이 오프닝 전 구간에 반영됐다.",
  "Intro updated","PIXEL's black mask with the blue X and BLUE NEWBIE's new design now run through the whole opening."),
]
