# -*- coding: utf-8 -*-
# LAST WAVE 사이트 콘텐츠 — 영웅·위협·아레나·소식. 그림은 대표가 만든 site_art 만 쓴다.

HEROES = [
 dict(id="pixel", name="PIXEL", ko="픽셀", role="MAIN", roleKo="주인공", hp=200, combo="20 · 25 · 30", art=True,
  tag_ko="WAVE와 깊은 관계가 있는 정체불명의 인물. 가면은 벗지 않는다.",
  tag_en="A figure of unknown origin, bound to the WAVE. The mask never comes off.",
  bio_ko=["손끝의 푸른 빛은 파도와 같은 것으로 만들어졌다. 그래서 파도를 밀어내고, 쓰러진 동료를 되살리고, 픽셀로 흩어졌다가 다시 모인다.",
          "서울역 지하 연구소의 기록에는 「PROJECT: PIXEL」이라는 이름이 남아 있다. 그는 만들어진 존재인가, 아니면 균열이 처음 열린 자리 그 자체인가.",
          "말이 없다. 대신 마지막 기술 BLUE PILLAR가 파도의 심장을 그대로 찌른다."],
  bio_en=["The blue light at his fingertips is made of the same thing as the wave. So he pushes the wave back, brings fallen allies up, scatters into pixels and reforms.",
          "Records from the lab beneath Seoul Station carry one name: PROJECT: PIXEL. Was he made — or is he the place where the rift first opened?",
          "He does not speak. His last skill, BLUE PILLAR, drives straight into the heart of the wave."],
  quote_ko="가면은 얼굴이 아니라 약속이다.", quote_en="The mask is not a face. It is a promise.",
  unmasked=("pixel_unmasked.jpg","가면 아래","UNDER THE MASK","가면을 벗은 PIXEL. 손끝의 푸른 불꽃은 파도와 같은 것으로 만들어졌다. 위험이 오면 가면은 픽셀처럼 다시 조립된다.","PIXEL without the mask. The blue flame at his fingertips is made of the same thing as the wave. When danger comes, the mask reassembles itself, pixel by pixel."),
  skills=[("Q","TSUNAMI","거대한 푸른 파도 100 + 넉백","A vast blue wave · 100 + knockback","wave"),
          ("E","TEAM HEAL","푸른 파동 회복 +80","Blue pulse · heal +80","pulse"),
          ("C","TELEPORT","푸른 픽셀로 흩어져 순간이동 · 무적","Scatter into pixels · blink · invulnerable","blink"),
          ("X","BLUE PILLAR","일반 워커 즉사 · 보스 2,500","Kills walkers outright · 2,500 to bosses","pillar")]),
 dict(id="bluenewbie", name="BLUE NEWBIE", ko="블루뉴비", role="MEDIC", roleKo="회복", hp=300, combo="15 · 15 · 25", art=True,
  tag_ko="회복 전문. 공격은 약하지만 버티는 힘이 누구보다 강하다.", tag_en="The medic. Weak strikes, the strongest will to stay standing.",
  bio_ko=["안경 너머로 팀 전체의 체력을 본다. 네 기술 전부가 「남을 살리는」 것이고, 그래서 영웅 중 유일하게 HP가 300이다.",
          "블루 웨빙 스트랩은 장식이 아니다. 밤새 뛰어다니며 쓰러진 사람을 끌어올린 흔적이다."],
  bio_en=["Behind the glasses he watches the whole team's health. All four skills exist to keep others alive — which is why he alone carries 300 HP.",
          "The blue webbing straps are not decoration. They are what is left after nights of dragging people back up."],
  quote_ko="내가 서 있는 한, 아무도 안 죽어.", quote_en="As long as I'm standing, nobody dies.",
  skills=[("Q","HEAL LINK","회복 링크 · 초당 +15 (8초)","Heal link · +15/s for 8s","link"),("E","HEAL BURST","즉시 +100 회복","Instant +100","burst"),
          ("C","LIFE SHIELD","100 흡수 보호막 · 깨지면 +50 회복","100 shield · +50 heal on break","shield"),("X","ALL HEAL","완전 회복 +200 · 무적 1초","Full heal +200 · 1s invulnerable","all")]),
 dict(id="alfred", name="ALFRED", ko="알프레드", role="DRAGONS", roleKo="더블 드래곤", hp=200, combo="18 · 18 · 35", art=True,
  tag_ko="양 어깨에 붙은 두 마리 네온 용과 함께 싸운다. 모든 기술은 용에서 나온다.", tag_en="Fights with two neon dragons on his shoulders. Every skill comes from them.",
  bio_ko=["푸른 용과 보라 용. 앞서 달리고, 포효하고, 몸을 감아 지키고, 적을 하늘로 끌고 가 내리꽂는다.", "후드의 「001」은 번호가 아니라 이름이다. 용은 무기가 아니라 동료다."],
  bio_en=["Blue and violet. They run ahead, roar, coil around him as a shield, and drag enemies into the sky to slam them down.", "The 001 on his hoodie is not a number, it is a name. The dragons are not weapons. They are company."],
  quote_ko="둘이 아니라 셋이야.", quote_en="Not two of us. Three.",
  skills=[("Q","RAINBOW DASH","두 용이 앞서 달린다 · 돌진 + 무지개 잔상 30×3","The dragons run ahead · charge + rainbow trail 30×3","dash"),
          ("E","SHOCKWAVE","두 용의 포효 · 충격파 80 + 넉백","Twin roar · shockwave 80 + knockback","wave"),
          ("C","PRISM SHIELD","용들이 몸을 감는다 · 방어막 100 · 깨지면 폭발 60","The dragons coil · shield 100 · bursts for 60","shield"),
          ("X","DRAGON FALL","두 용이 적을 물어 하늘로 끌고 가 내리꽂는다 1,000","Both dragons drag the enemy skyward and slam it down · 1,000","pillar")]),
 dict(id="line", name="LINE", ko="라인", role="BLADE", roleKo="대검", hp=200, combo="25 · 30 · 45", art=True,
  tag_ko="거대한 대검. 직육면체 머리는 헬멧이 아니라 그 자체가 얼굴이다.", tag_en="A giant blade. The block-shaped head is not a helmet — it is the face.",
  bio_ko=["검을 키우고, 바닥에서 불러내고, 적을 검 쪽으로 끌어당기고, 열다섯 자루를 연속으로 던진다.", "표정이 없어서 가장 무섭다. 어디서 왔는지 아무도 묻지 않았다."],
  bio_en=["Grows the blade, calls blades up from the ground, pulls enemies toward it, throws fifteen in a row.", "No expression — which is what makes him the most frightening. Nobody ever asked where he came from."],
  quote_ko="선을 넘었으면, 잘린다.", quote_en="Cross the line, and you're cut.",
  skills=[("Q","GIANT BLADE","검이 거대해진다 · 공격 +60% · 주변 10","The blade grows · +60% attack · 10 around","blade"),("E","BLADE SUMMON","바닥에서 검 소환 · 적마다 40","Blades from the ground · 40 each","summon"),
          ("C","MAGNET BLADE","적들을 검 쪽으로 끌어당김 20","Pulls enemies to the blade · 20","magnet"),("X","15 BLADES","검 15자루 연속 투척 70×15","Fifteen blades thrown · 70×15","multi")]),
 dict(id="iris", name="IRIS", ko="아이리스", role="PORTAL", roleKo="포털", hp=200, combo="15 · 20 · 25", art=True,
  tag_ko="경계를 여는 사람. 포털로 길을 만들고, 누구도 그다음 수를 읽지 못한다.", tag_en="She opens the borders. Portals make the path, and nobody reads her next move.",
  bio_ko=["헤드폰을 목에 건 채 균열 한가운데를 걷는다. 그녀에게 벽은 벽이 아니라 아직 열지 않은 문이다.",
          "포털로 동료를 옮기고, 적을 엉뚱한 곳으로 떨어뜨린다. 예측할 수 없다는 것이 그녀의 가장 큰 무기다."],
  bio_en=["She walks through the middle of the rift, headphones around her neck. To her a wall is not a wall — just a door not yet opened.",
          "She moves allies through portals and drops enemies somewhere they never meant to be. Being unpredictable is her sharpest weapon."],
  quote_ko="경계는, 내가 정해.", quote_en="I decide where the border is.",
  skills=[("Q","PORTAL","두 지점을 잇는 포털 · 아군 이동","A portal linking two points · moves allies","link"),
          ("E","BLINK","짧은 순간이동 · 잠시 무적","Short-range blink · brief invulnerability","blink"),
          ("C","SAFE ZONE","포털 방벽 · 아군 받는 피해 30% 감소 4초","Portal barrier · −30% damage to allies for 4s","shield"),
          ("X","NEW DIMENSION","거대한 차원문 · 적을 삼켰다 무작위로 떨어뜨림 60","A vast rift gate · swallows enemies and drops them at random · 60","burst")]),
]

# 원화(팀 아트) 기준 영웅은 다섯 — ROOKIE 는 사이트에서 뺌 (2026-09-25 대표 확정). 되돌리려면 HEROES 로 옮긴다.
RETIRED = [
 dict(id="rookie", name="ROOKIE", ko="루키", role="STARTER", roleKo="시작", hp=200, combo="15 · 15 · 20", art=True,
  tag_ko="WAVE가 시작된 그날, 평범한 생존자였던 그는 살아남기 위해 싸우기 시작했다.", tag_en="On the day the WAVE began, an ordinary survivor started fighting to stay alive.",
  bio_ko=["기술이 아니라 몸으로 싸운다. 대시, 펀치, 가드 — 그리고 10초의 각성.", "모든 플레이어가 처음 만나는 얼굴. 강남에서 친구들을 잃고, 지하철 입구에서 처음 워커를 쓰러뜨렸다."],
  bio_en=["He fights with his body, not with tricks. Dash, punch, guard — and ten seconds of awakening.", "The first face every player meets. Lost his friends in Gangnam, dropped his first walker at the station entrance."],
  quote_ko="도망치는 것도 싸우는 거다. 오늘까지는.", quote_en="Running is fighting too. Until today.",
  skills=[("Q","DASH","전방 대시 · 잠시 무적","Forward dash · brief invulnerability","dash"),("E","POWER PUNCH","강력한 펀치 40","Heavy punch · 40","punch"),
          ("C","GUARD","2초간 받는 피해 50% 감소","−50% damage taken for 2s","guard"),("X","FULL POWER","10초 각성 · 공격 +50% · 속도 +30%","10s awakening · +50% attack · +30% speed","power")]),
]

THREATS = [
 dict(id="lurker", name="LURKER", ko="러커", wave=1, hp=80, dmg=10, speed="보통", speed_en="Normal", kind="근접", kind_en="Melee",
  ko_d="가장 먼저 오는 것. 어둠에서 태어나, 어둠으로 돌아간다.", en_d="The first to come. Born from the dark, returning to it."),
 dict(id="runner", name="RUNNER", ko="러너", wave=3, hp=60, dmg=8, speed="매우 빠름", speed_en="Very fast", kind="근접", kind_en="Melee",
  ko_d="중거리에서 한 번씩 달려든다. 잔상이 보이면 이미 늦다.", en_d="Lunges from mid range. If you see the afterimage, it is already too late."),
 dict(id="brute", name="BRUTE", ko="브루트", wave=5, hp=500, dmg=35, speed="느림", speed_en="Slow", kind="강타", kind_en="Heavy",
  ko_d="느리지만 한 방이 35. 바위가 걸어온다.", en_d="Slow, but one blow is 35. The rock walks."),
 dict(id="spitter", name="SPITTER", ko="스피터", wave=7, hp=100, dmg=15, speed="느림", speed_en="Slow", kind="원거리", kind_en="Ranged",
  ko_d="거리를 두고 뱉는다. 초록빛을 보면 옆으로.", en_d="Keeps its distance and spits. Green light — step aside."),
 dict(id="crawler", name="CRAWLER", ko="크롤러", wave=8, hp=120, dmg=20, speed="빠름", speed_en="Fast", kind="기어옴", kind_en="Crawler",
  ko_d="낮게, 빠르게. 바닥을 보지 않으면 먼저 물린다.", en_d="Low and fast. Watch the ground or it bites first."),
 dict(id="hunter", name="HUNTER", ko="헌터", wave=11, hp=250, dmg=30, speed="빠름", speed_en="Fast", kind="근접", kind_en="Melee",
  ko_d="선로 위를 달린다. 그들은 PIXEL만 노린다.", en_d="Runs the rails. They hunt only PIXEL."),
 dict(id="reaper", name="REAPER", ko="리퍼", wave=16, hp=400, dmg=40, speed="보통", speed_en="Normal", kind="강타", kind_en="Heavy",
  ko_d="후반의 벽. 낫이 푸르게 빛나면 한 명은 사라진다.", en_d="The late-game wall. When the scythe glows blue, someone is gone."),
]
BOSSES = [
 dict(id="themarked", name="THE MARKED", ko="표식을 가진 자", wave=10, hp=3000, dmg=25, phases=1,
  ko_d="광화문 광장에서 기다린다. 가면의 문양이 PIXEL의 것과 같다.", en_d="Waits in Gwanghwamun Square. The sigil on its face matches PIXEL's mask."),
 dict(id="voidtitan", name="VOID TITAN", ko="보이드 타이탄", wave=20, hp=5000, dmg=30, phases=3,
  ko_d="롯데타워가 균열을 붙잡고 있다. 그 위에 타이탄이 있다. 3페이즈.", en_d="Lotte Tower holds the rift shut. The Titan stands on top of it. Three phases."),
 dict(id="abyssking", name="THE ABYSS KING", ko="심연의 왕", wave=30, hp=15000, dmg=35, phases=2,
  ko_d="모든 차원의 끝, 끝없는 공허에서 태어났다. 그가 서면 공간이 뒤틀리고, 체력이 절반 아래로 떨어지면 몸이 변형된다.",
  en_d="Born in the endless void at the edge of every dimension. Space twists where he stands; below half health his body transforms.",
  quote_ko="이 세계의 끝은 내가 만든 심연이다.", quote_en="The end of this world is an abyss of my making.",
  plist=[("PHASE 1","심연의 군주 — 원거리·근거리 공격으로 전장을 압도한다.","Lord of the Abyss — overwhelms the field at range and up close."),
         ("PHASE 2","진화한 심연의 왕 — 공격 속도와 이동 속도가 크게 오르고, 심연의 폭주가 추가된다.","The Evolved King — much faster attacks and movement; Abyssal Frenzy unlocks.")],
  moves_ko="공허의 구체 · 중력 붕괴 · 심연의 낫 · 공허의 파도 · 차원의 균열 · 심연의 폭주", moves_en="Void Orbs · Gravity Collapse · Abyssal Scythe · Void Wave · Dimensional Rift · Abyssal Frenzy",
  weak_ko="빛 속성 · PIXEL의 BLUE PILLAR", weak_en="Light · PIXEL's BLUE PILLAR"),
 dict(id="voidheart", name="HEART OF THE VOID", ko="공허의 심장", wave=50, hp=30000, dmg=40, phases=3,
  ko_d="공허의 깊은 곳에서 태어난 존재. 모든 차원을 삼키고 새로운 우주를 만들려 한다. 심연의 왕조차 두려워하는 공허의 핵심.",
  en_d="Born deep in the void. It would swallow every dimension and build a new universe. Even the Abyss King fears it.",
  quote_ko="모든 공허의 끝자락, 그 중심에 내가 있다.", quote_en="At the far edge of every void, I am the center.",
  plist=[("PHASE 1","공허 에너지를 모아 광역 공격을 퍼붓는다.","Gathers void energy into wide-area strikes."),
         ("PHASE 2","심장을 드러내고 모든 능력이 강화된다. 이동과 공격이 빨라진다.","Bares its heart; every ability strengthens, faster movement and attacks."),
         ("PHASE 3","심장이 완전히 열리며 공허 그 자체가 되어 모든 것을 삼키려 한다.","The heart opens fully; it becomes the void itself and tries to swallow everything.")],
  moves_ko="공허 붕괴 · 차원의 찢김 · 공허 폭풍 · 심장 광선 · 공허 소환 · 종말의 포식", moves_en="Void Collapse · Dimension Tear · Void Storm · Heart Beam · Void Summon · Final Devour",
  weak_ko="빛 속성 · PIXEL의 BLUE PILLAR (심장이 열릴 때)", weak_en="Light · PIXEL's BLUE PILLAR (when the heart opens)"),
 dict(id="creator", name="CREATOR OF DESPAIR", ko="절망의 창조자", wave=100, hp=50000, dmg=50, phases=4, final=True,
  ko_d="모든 차원과 세계, 존재와 시간조차 그의 손끝에서 태어났다. 끝없는 창조에 지친 그는 절망을 알게 되었고, 모든 세계를 영원한 침묵으로 되돌리려 한다.",
  en_d="Every dimension, world, being and even time was born at his fingertips. Worn out by endless creation he learned despair, and now he would return every world to eternal silence.",
  quote_ko="너희의 세계도, 너희 자신조차도 내 절망의 일부에 불과하다.", quote_en="Your world, and you yourselves, are only part of my despair.",
  plist=[("PHASE 1","창조의 권능 — 차원을 창조하고 붕괴시키며 거대한 에너지를 쏟아낸다.","Power of Creation — builds and collapses dimensions, pouring out vast energy."),
         ("PHASE 2","절망의 폭주 — 모든 능력이 강화되고 패턴을 예측할 수 없게 된다.","Rampage of Despair — every ability grows and the patterns turn unpredictable."),
         ("PHASE 3","파멸의 강림 — 시공간을 왜곡해 지속 피해와 압도적인 공격을 가한다.","Descent of Ruin — warps space-time for constant damage and crushing attacks."),
         ("PHASE 4","최후의 절망 — 마지막 힘으로 플레이어를 절망 속으로 끌어들인다. 여기서 끝낸다.","Final Despair — drags the players into despair with the last of its power. End it here.")],
  moves_ko="차원 붕괴 · 절망의 광선 · 운명의 심판 · 차원 추방 · 절망의 손아귀 · 종말의 심연", moves_en="Dimension Collapse · Beam of Despair · Judgment of Fate · Dimensional Exile · Grip of Despair · Abyss of the End",
  weak_ko="빛 속성 · PIXEL의 BLUE PILLAR · 네 명의 연계", weak_en="Light · PIXEL's BLUE PILLAR · all four together"),
]

ARENAS = [
 ("GANGNAM","강남 폐허 거리","1–5","균열이 열린 날, 나는 강남에 있었다. 친구들은… 보이지 않는다.","The day the rift opened, I was in Gangnam. My friends… gone."),
 ("STATION","지하철 입구 광장","6–10","지하로 내려간 사람들은 돌아오지 않았다. 워커는 어둠에서 태어난다.","Those who went underground never came back. Walkers are born in the dark."),
 ("HAN RIVER","한강 다리","11–15","다리를 건너면 북쪽이다. 남산타워가 부러진 채 서 있다.","Across the bridge is the north. Namsan Tower stands, broken."),
 ("MYEONGDONG","명동 거리","16–20","명동은 조용했다. 조용한 곳이 가장 위험하다.","Myeongdong was quiet. Quiet places are the most dangerous."),
 ("HONGDAE","홍대 거리","21–25","네온이 아직 깜박인다. 누군가 여기서 마지막 밤을 보냈다.","The neon still flickers. Someone spent their last night here."),
 ("GWANGHWAMUN","광화문 광장","26–30","THE MARKED가 여기서 나를 기다린다. 가면의 문양이… 내 것과 같다.","THE MARKED waits for me here. The sigil on its face… is mine."),
 ("SEOUL STATION","서울역 광장","31–35","PROJECT: PIXEL — 서울역 지하 연구소의 기록. 나는… 만들어진 존재였나.","PROJECT: PIXEL — records from the lab beneath Seoul Station. Was I… made?"),
 ("PLATFORM","지하철 승강장","36–40","HUNTER들이 선로 위를 달린다. 그들은 나만 노린다.","HUNTERS run the rails. They hunt only me."),
 ("BUKCHON","북촌 한옥마을","41–45","가장 오래된 골목. 균열이 처음 열린 곳은 여기가 아니다 — 나였다.","The oldest alley. The rift did not open here first — it opened in me."),
 ("LOTTE TOWER","잠실 롯데타워","46–49","타워가 균열을 붙잡고 있다. VOID TITAN이 그 위에 있다.","The tower holds the rift. VOID TITAN stands on top."),
 ("THE RIFT","균열 내부","50","균열 안. 여기서 끝낸다.","Inside the rift. It ends here."),
]

NEWS = [
 ("2026-09-25","새 영웅 IRIS · 다섯 영웅 확정","포털을 여는 아이리스가 합류했다. 팀 원화 그대로 PIXEL · LINE · BLUE NEWBIE · ALFRED · IRIS, 영웅은 다섯. 「경계는, 내가 정해.」",
  "New hero: IRIS · the five","IRIS, the portal-opener, joins. Straight from the team art: PIXEL, LINE, BLUE NEWBIE, ALFRED and IRIS — five heroes. “I decide where the border is.”"),
 ("2026-09-24","영웅 5명 전원 · 새 보스 3종","BLUE NEWBIE · ROOKIE · LINE의 키아트가 나오며 영웅 다섯 명이 모두 모였다. 심연의 왕(웨이브 30), 공허의 심장(웨이브 50), 최종 보스 절망의 창조자(웨이브 100)를 공개한다.",
  "All five heroes · three new bosses","Key art for BLUE NEWBIE, ROOKIE and LINE completes the roster of five. Revealing The Abyss King (wave 30), Heart of the Void (wave 50) and the final boss, Creator of Despair (wave 100)."),
 ("2026-09-24","캐릭터 아트 1차 공개","PIXEL · ALFRED와 적 7종, 보스 2종의 키아트가 나왔다. BLUE NEWBIE · ROOKIE · LINE은 원본 디자인 기준으로 제작 중.",
  "First character art","Key art for PIXEL, ALFRED, seven enemies and two bosses. BLUE NEWBIE, ROOKIE and LINE are in production from their original designs."),
 ("2026-09-23","리얼 3D로 간다","스타일라이즈드 목업을 기각하고 반실사 3D(Unity)로 전환했다. 천천히 가더라도 제대로. 3D 초판은 영웅 2 · 적 3 · 보스 1.",
  "Going real-3D","Stylized mockups were rejected; the game moves to semi-realistic 3D in Unity. Slowly, but properly. First 3D cut: 2 heroes, 3 enemies, 1 boss."),
 ("2026-09-24","인트로 영상 갱신","PIXEL의 검은 가면과 블루 X, BLUE NEWBIE의 새 디자인이 오프닝 전 구간에 반영됐다.",
  "Intro updated","PIXEL's black mask with the blue X and BLUE NEWBIE's new design now run through the whole opening."),
]
